### ISSUE TITLE
Fails on Blender 4.1

### ISSUE THREAD

**Issue by Wizzerinus** [loonaticx/MAYBEE#5]
Trying to export the default cube + BSDF node, this happens:

```
Objects for export: ['Cube']
Traceback (most recent call last):
  File "/home/wizzerinus/.config/blender/4.2/scripts/addons/yabee/yabee_libs/egg_writer.py", line 136, in make_hierarchy_from_list
    group = self.__class__(obj)
  File "/home/wizzerinus/.config/blender/4.2/scripts/addons/yabee/yabee_libs/egg_writer.py", line 60, in __init__
    self._yabee_object = EGGMeshObjectData(self.object)
                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/wizzerinus/.config/blender/4.2/scripts/addons/yabee/yabee_libs/egg_writer.py", line 397, in __init__
    self.smooth_vtx_list = self.get_smooth_vtx_list()
                           ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/wizzerinus/.config/blender/4.2/scripts/addons/yabee/yabee_libs/egg_writer.py", line 442, in get_smooth_vtx_list
    if self.obj_ref.data.use_auto_smooth:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
```

It seems that `use_auto_smooth` no longer exists since 4.1.

**Comment by Wizzerinus** [comment]
Apologies, it seems that I'm not actually on MAYBEE :(
